# -*- coding: utf-8 -*-
"""
导出主库 ops 权威表为幂等 upsert SQL（deploy/ops_data.sql）。

远端 remote_deploy.sh 会把该文件拷入数据卷，并在容器内执行
deploy/ops_data_sync.py 导入云端主库：按 id 覆盖配置表，
不触碰空间/用户/错题等真实数据。TABLES 易扩展。

用法：python tools/deploy_export_ops.py
"""
import os
import sqlite3
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
MAIN_DB = os.path.join(ROOT, "backend", "easyfix_main.db")
OUT = os.path.join(ROOT, "deploy", "ops_data.sql")

# 主库 ops 权威表（配置数据，按 id 幂等 upsert）
TABLES = [
    "grammar_lesson",      # 语法教程（Ops 权威源，44 条）
    "star_action",         # 激励动作规则（11 条 PRESET）
    "achievement",         # 成就定义（19 条）
    "achievement_config",  # 成就配置（3 条）
]


def esc(v):
    """SQL 字面量转义。"""
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main() -> int:
    if not os.path.isfile(MAIN_DB):
        print("!! 主库不存在: %s（跳过导出）" % MAIN_DB, file=sys.stderr)
        return 1
    con = sqlite3.connect(MAIN_DB)
    lines = [
        "-- EasyFix ops authority data (generated by tools/deploy_export_ops.py)",
        "-- 幂等 upsert：按 id 覆盖配置表，不触碰空间/用户/错题等数据",
        "",
    ]
    total = 0
    for t in TABLES:
        try:
            cols = [r[1] for r in con.execute("PRAGMA table_info(%s)" % t)]
        except Exception as e:  # pragma: no cover
            print("!! 表 %s 读取失败: %s" % (t, e), file=sys.stderr)
            continue
        if not cols:
            print("!! 表 %s 不存在或无列，跳过" % t, file=sys.stderr)
            continue
        rows = con.execute("SELECT * FROM %s" % t).fetchall()
        for row in rows:
            idv = row[0]
            vals = ", ".join(esc(v) for v in row)
            upd = ", ".join("%s=excluded.%s" % (c, c) for c in cols[1:])
            lines.append(
                "INSERT INTO %s (%s) VALUES (%s) "
                "ON CONFLICT(id) DO UPDATE SET %s;" % (t, ", ".join(cols), vals, upd)
            )
        total += len(rows)
        print("   %s: %d 条已导出" % (t, len(rows)))
    con.close()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("已生成: %s（共 %d 条 upsert）" % (OUT, total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
